version: '3'
services:
  web:
    build: .
    image: danielhollands
    command: ['middleman', 'server']
    volumes:
      - .:/usr/src/app:cached
    ports:
      - "4567:4567"
      - "35729:35729"
